import esbuild from "esbuild";
import process from "process";
import { copyFileSync, mkdirSync, existsSync } from "fs";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === "production";

// Dev: copy output to vault for live testing
const vaultPluginDir = process.env.VAULT_PLUGIN_DIR;

function copyToVault() {
  if (!vaultPluginDir) return;
  if (!existsSync(vaultPluginDir)) {
    mkdirSync(vaultPluginDir, { recursive: true });
  }
  copyFileSync("main.js", `${vaultPluginDir}/main.js`);
  copyFileSync("manifest.json", `${vaultPluginDir}/manifest.json`);
  if (existsSync("styles.css")) {
    copyFileSync("styles.css", `${vaultPluginDir}/styles.css`);
  }
}

const copyPlugin = {
  name: "copy-to-vault",
  setup(build) {
    build.onEnd(() => {
      if (!vaultPluginDir) return;
      try {
        copyToVault();
        console.log("Copied to vault plugin directory");
      } catch (e) {
        console.error("Failed to copy to vault:", e.message);
      }
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [copyPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
